### ISSUE TITLE
Should update values for the reason key.

### ISSUE THREAD

**Issue by cia-rana** [kayac/Gunfish#32]
Values for the APNs JSON `reason` key have changed and thus we should update `ErrorMessage const` in [github.com/kayac/Gunfish/apns/error.go](https://github.com/kayac/Gunfish/blob/master/apns/error.go).

Previous documentation(web.archive.org because that page cannot be found.): 
https://web.archive.org/web/20160902182330/https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html

Current documentation:
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html

**Comment by takyoshi** [comment]
@cia-rana Thank you for the issue. I will fix it at #33.
